apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: test
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'python-test-web-app-metrics'
        static_configs:
          - targets: ['python-test-web-app:8080']
